### ISSUE TITLE
Problems with iRODS 4.3.2 and PAM

### ISSUE THREAD

**Issue by jnimoth** [cyverse/irodsfs#39] opened 2024-09-03 09:54 UTC
Hi Illyoung,
I have problems when trying to use irodsfs v0.9.7 with iRODS v4.3.2. 

We had previously iRODS 4.2.11 where everything worked fine with this config yaml:

```
host: store.data.rug.nl
port: 1247
proxy_user: user@rug.nl
client_user: user@rug.nl
zone: rug
password:

auth_scheme: "pam" 
ssl_ca_cert_file: "/etc/ssl/certs/ca-certificates.crt"
ssl_encryption_key_size: 32
ssl_encryption_algorithm: "AES-256-CBC"
ssl_encryption_salt_size: 8
ssl_encryption_hash_rounds: 16

path_mappings:
  - irods_path: /rug/home/user@rug.nl
    mapping_path: /
    resource_type: dir
```

But when I use this config file for our test instance which now runs 4.3.2, I get the following.
First, I used this config file:

```
host: store-test.data.rug.nl
port: 1247
proxy_user: user@rug.nl
client_user: user@rug.nl
zone: testrug
password:

auth_scheme: "pam" 
ssl_ca_cert_file: "/etc/ssl/certs/ca-certificates.crt"
ssl_encryption_key_size: 32
ssl_encryption_algorithm: "AES-256-CBC"
ssl_encryption_salt_size: 8
ssl_encryption_hash_rounds: 16

path_mappings:
  - irods_path: /testrug/home/user@rug.nl
    mapping_path: /
    resource_type: dir
```

which gives me this error:

```
./irodsfs --config ~/.irods/config2.yaml ~/irods_mount/
time="2024-09-03 11:39:41.811706" level=info msg="Logging to \"/home/jelte/git_projects/irodsfs_binaries/latest/crbdinbg7o0prmgibdc0.log.parent\"" function=ProcessCommonFlags package=commons
Password: 
time="2024-09-03 11:39:49.179000" level=info msg="Found FUSE Device. Starting iRODS FUSE Lite." function=parentMain package=main
time="2024-09-03 11:39:49.179078" level=info msg="Running the child process in the background mode" function=RunChildProcess package=commons
time="2024-09-03 11:39:49.179815" level=info msg="Child process id = 496235" function=RunChildProcess package=commons
time="2024-09-03 11:39:49.179885" level=info msg="Sending configuration via STDIN" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.180236" level=info msg="Successfully sent configuration to STDIN" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.190756" level=info msg="time=\"2024-09-03 11:39:49.190660\" level=info msg=\"Start child process\" function=childMain package=main" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.190771" level=info msg="time=\"2024-09-03 11:39:49.190699\" level=info msg=\"Check STDIN to communicate to other process\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.190776" level=info msg="time=\"2024-09-03 11:39:49.190708\" level=info msg=\"Reading configuration from STDIN\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.190782" level=info msg="time=\"2024-09-03 11:39:49.190719\" level=info msg=\"Successfully read configuration from STDIN\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:50.605156" level=error msg="failed to start child process" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:39:50.605380" level=error msg="failed to send configuration to iRODS FUSE Lite child process:\n    main.parentMain\n        /github/workspace/cmd/main.go:131\n  - failed to start child process:\n    github.com/cyverse/irodsfs/cmd/commons.ParentProcessSendConfigViaSTDIN\n        /github/workspace/cmd/commons/daemon.go:143" function=parentMain package=main
```

and here also the content of the `*.log.child` which is created:

```
time="2024-09-03 11:39:49.190983" level=info msg="Logging to \"/home/jelte/git_projects/irodsfs_binaries/latest/crbdinbg7o0prmgibdc0.log.child\"" function=ChildProcessReadConfigViaSTDIN package=commons
time="2024-09-03 11:39:49.191082" level=info msg="Run child process" function=childMain package=main
time="2024-09-03 11:39:49.191091" level=info msg="iRODS FUSE Lite version \"v0.9.7\", commit \"c1c7151cabac75aaae20f821a38f3f38753f0fe6\"" function=run package=main
time="2024-09-03 11:39:49.191107" level=info msg="Connect to IRODS server using \"pam\" auth scheme" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:49.191113" level=info msg="PAM requires SSL, enabling CS negotiation" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:49.191119" level=info msg="Initializing an iRODS file system client" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:49.191128" level=info msg="Initializing an iRODS native file system client" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:49.191170" level=info msg="Initializing virtual path mappings" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:49.191176" level=info msg="Building a hierarchy" function=NewVPathManager package=vpath
time="2024-09-03 11:39:49.191181" level=info msg="Building a VPath Entry - /testrug/home/user@rug.nl" function=buildOne package=vpath struct=VPathManager
time="2024-09-03 11:39:50.604461" level=error msg="failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=Connect package=connection struct=IRODSConnection
time="2024-09-03 11:39:50.604676" level=error msg="failed to check path - /testrug/home/user@rug.nl" error="failed to connect to irods server: failed to login to irods: received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO): authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=buildOne package=vpath struct=VPathManager
time="2024-09-03 11:39:50.604715" level=info msg="Initializing File Handle Map" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:50.604839" level=error msg="failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=NewFileSystem package=irodsfs
time="2024-09-03 11:39:50.604965" level=error msg="failed to create the filesystem:\n    main.run\n        /github/workspace/cmd/main.go:226\n  - failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=run package=main
time="2024-09-03 11:39:50.605108" level=error msg="failed to run iRODS FUSE Lite:\n    main.childMain\n        /github/workspace/cmd/main.go:175\n  - failed to create the filesystem:\n    main.run\n        /github/workspace/cmd/main.go:226\n  - failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=childMain package=main
```

I [did see ](https://docs.irods.org/4.3.2/plugins/pluggable_authentication/#user-setup)that iRODS 4.3.x also requires in the `irods_environment.json` file that "PAM" is changed to "pam_password". I also adjusted that in my config yaml and then tried again, but the issue is the same.

Here what I got after changing to "pam_password":

```
$ ./irodsfs --config ~/.irods/config3.yaml ~/irods_mount/
time="2024-09-03 11:48:42.809716" level=info msg="Logging to \"/home/jelte/git_projects/irodsfs_binaries/latest/crbdmujg7o0ri068dv40.log.parent\"" function=ProcessCommonFlags package=commons
Password: 
time="2024-09-03 11:48:50.703928" level=info msg="Found FUSE Device. Starting iRODS FUSE Lite." function=parentMain package=main
time="2024-09-03 11:48:50.704028" level=info msg="Running the child process in the background mode" function=RunChildProcess package=commons
time="2024-09-03 11:48:50.704608" level=info msg="Child process id = 505235" function=RunChildProcess package=commons
time="2024-09-03 11:48:50.704634" level=info msg="Sending configuration via STDIN" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.704944" level=info msg="Successfully sent configuration to STDIN" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.714011" level=info msg="time=\"2024-09-03 11:48:50.713882\" level=info msg=\"Start child process\" function=childMain package=main" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.714028" level=info msg="time=\"2024-09-03 11:48:50.713904\" level=info msg=\"Check STDIN to communicate to other process\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.714033" level=info msg="time=\"2024-09-03 11:48:50.713909\" level=info msg=\"Reading configuration from STDIN\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.714038" level=info msg="time=\"2024-09-03 11:48:50.713914\" level=info msg=\"Successfully read configuration from STDIN\" function=ChildProcessReadConfigViaSTDIN package=commons" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:52.141960" level=error msg="failed to start child process" function=ParentProcessSendConfigViaSTDIN package=commons
time="2024-09-03 11:48:52.142254" level=error msg="failed to send configuration to iRODS FUSE Lite child process:\n    main.parentMain\n        /github/workspace/cmd/main.go:131\n  - failed to start child process:\n    github.com/cyverse/irodsfs/cmd/commons.ParentProcessSendConfigViaSTDIN\n        /github/workspace/cmd/commons/daemon.go:143" function=parentMain package=main

```

And the *.log.child
```
time="2024-09-03 11:48:50.714085" level=info msg="Logging to \"/home/jelte/git_projects/irodsfs_binaries/latest/crbdmujg7o0ri068dv40.log.child\"" function=ChildProcessReadConfigViaSTDIN package=commons
time="2024-09-03 11:48:50.714133" level=info msg="Run child process" function=childMain package=main
time="2024-09-03 11:48:50.714138" level=info msg="iRODS FUSE Lite version \"v0.9.7\", commit \"c1c7151cabac75aaae20f821a38f3f38753f0fe6\"" function=run package=main
time="2024-09-03 11:48:50.714149" level=info msg="Connect to IRODS server using \"pam\" auth scheme" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:50.714151" level=info msg="PAM requires SSL, enabling CS negotiation" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:50.714154" level=info msg="Initializing an iRODS file system client" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:50.714156" level=info msg="Initializing an iRODS native file system client" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:50.714186" level=info msg="Initializing virtual path mappings" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:50.714192" level=info msg="Building a hierarchy" function=NewVPathManager package=vpath
time="2024-09-03 11:48:50.714195" level=info msg="Building a VPath Entry - /testrug/home/user@rug.nl" function=buildOne package=vpath struct=VPathManager
time="2024-09-03 11:48:52.141035" level=error msg="failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=Connect package=connection struct=IRODSConnection
time="2024-09-03 11:48:52.141309" level=error msg="failed to check path - /testrug/home/user@rug.nl" error="failed to connect to irods server: failed to login to irods: received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO): authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=buildOne package=vpath struct=VPathManager
time="2024-09-03 11:48:52.141355" level=info msg="Initializing File Handle Map" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:52.141572" level=error msg="failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=NewFileSystem package=irodsfs
time="2024-09-03 11:48:52.141730" level=error msg="failed to create the filesystem:\n    main.run\n        /github/workspace/cmd/main.go:226\n  - failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=run package=main
time="2024-09-03 11:48:52.141919" level=error msg="failed to run iRODS FUSE Lite:\n    main.childMain\n        /github/workspace/cmd/main.go:175\n  - failed to create the filesystem:\n    main.run\n        /github/workspace/cmd/main.go:226\n  - failed to list groups for a user \"user@rug.nl\":\n    github.com/cyverse/irodsfs/irodsfs.NewFileSystem\n        /github/workspace/irodsfs/fs.go:235\n  - failed to get a connection from the pool because pending error is found:\n    github.com/cyverse/go-irodsclient/irods/session.(*IRODSSession).AcquireConnection\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/session.go:238\n  - failed to connect to irods server:\n    github.com/cyverse/go-irodsclient/irods/session.(*ConnectionPool).Get\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/session/pool.go:202\n  - failed to login to irods:\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).Connect\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:289\n  - received irods authentication error (CAT_SUCCESS_BUT_WITH_NO_INFO):\n    github.com/cyverse/go-irodsclient/irods/connection.(*IRODSConnection).login\n        /go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.6/irods/connection/connection.go:510\n  - authentication error (auth scheme: 'pam', username: 'user@rug.nl', zone: 'testrug')" function=childMain package=main
```

Can it be that this issue relates to the change made for the pam authentication between 4.2.11 and 4.3.x?
I can login to the 4.3.2 server successfully via icommands using "pam_password"

**Comment by iychoi** [comment] 2024-09-03 17:16
It looks like there's a change in iRODS v4.3.2. I'll check it soon.

**Comment by iychoi** [comment] 2024-09-03 17:18
Can I get a test account on your system? CyVerse does not have PAM enabled iRODS 4.3.2 system.

**Comment by iychoi** [comment] 2024-09-13 16:53
The issue is fixed in go-irodsclient. 
I hope the new release fixes the issue.

https://github.com/cyverse/irodsfs/releases/tag/v0.10.0

Please reopen this if the issue persists.

**Closed by iychoi** 2024-09-13 16:53 UTC
Labels: bug
