### ISSUE TITLE
Transfering large files over 16GB fails

### ISSUE THREAD

**Issue by praveenivp** [cyverse/irodsfs#31] opened 2023-02-10 13:50 UTC
Hi iychoi, 

I'm an end user of irodsfs to download MRI data files from our iRODS server. When I download  large files (>16 GB), the copying freezes always around  16,996,139,008  bytes. Are you aware of this issue? Can I fix it with better config? Let me know if you need more information.

Thanks a lot for your help
Praveen

``` bash
[user@login0 test]$ rsync -av --info=progress2,stats2 ~/iRODS/user/randdata/file_16GB.dat .
sending incremental file list
file_16GB.dat
 16,777,216,000 100%   20.86MB/s    0:12:47 (xfr#1, to-chk=0/1)

Number of files: 1 (reg: 1)
Number of created files: 1 (reg: 1)
Number of deleted files: 0
Number of regular files transferred: 1
Total file size: 16,777,216,000 bytes
Total transferred file size: 16,777,216,000 bytes
Literal data: 16,777,216,000 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.011 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 16,781,312,103
Total bytes received: 35

sent 16,781,312,103 bytes  received 35 bytes  21,864,901.81 bytes/sec
total size is 16,777,216,000  speedup is 1.00

[user@login0 test]$ dd if=/dev/urandom of=~/iRODS/user/randdata/file_17GB.dat bs=10M count=1700
[user@login0 test]$ rsync -av --info=progress2,stats2 ~/iRODS/user/randdata/file_17GB.dat .
sending incremental file list
file_17GB.dat
 16,996,139,008  95%   20.03MB/s    0:00:40   # freezes here
```

<details>
  <summary>log file</summary>

```bash
time="2023-02-10 13:57:05.312142" level=info msg="Calling Lookup (46) - /user/randdata/file_16GB.dat" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 13:57:05.322432" level=info msg="Called Lookup (46) - /user/randdata/file_16GB.dat" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 13:57:05.322503" level=info msg="Calling Attr (47) - /user/randdata/file_16GB.dat" function=Attr package=irodsfs struct=File
time="2023-02-10 13:57:05.322535" level=info msg="Called Attr (47) - /user/randdata/file_16GB.dat" function=Attr package=irodsfs struct=File
time="2023-02-10 13:57:05.325147" level=info msg="Calling Open (48) - /user/randdata/file_16GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-10 13:57:05.336313" level=info msg="Called Open (48) - /user/randdata/file_16GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-10 14:10:12.745304" level=info msg="Calling Attr (49) - /" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.751457" level=info msg="Checking ACL info for /MRDataZone/home" function=mapDirACL package=irodsfs
time="2023-02-10 14:10:12.756240" level=info msg="Checked ACL info for /MRDataZone/home, 0 ACL entries" function=mapDirACL package=irodsfs
time="2023-02-10 14:10:12.756277" level=info msg="Called Attr (49) - /" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.756472" level=info msg="Calling Lookup (50) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.759824" level=info msg="Called Lookup (50) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.759859" level=info msg="Calling Attr (51) - /user" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.759883" level=info msg="Called Attr (51) - /user" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.760145" level=info msg="Calling Lookup (52) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.760196" level=info msg="Called Lookup (52) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.760214" level=info msg="Calling Attr (53) - /user" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.760233" level=info msg="Called Attr (53) - /user" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.760346" level=info msg="Calling Lookup (54) - /user/randdata" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.763707" level=info msg="Called Lookup (54) - /user/randdata" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.763743" level=info msg="Calling Attr (55) - /user/randdata" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.763770" level=info msg="Called Attr (55) - /user/randdata" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.764284" level=info msg="Calling ReadDirAll (56) - /user/randdata" function=ReadDirAll package=irodsfs struct=Dir
time="2023-02-10 14:10:12.780398" level=info msg="Called ReadDirAll (56) - /user/randdata" function=ReadDirAll package=irodsfs struct=Dir
time="2023-02-10 14:10:12.780796" level=info msg="Calling Lookup (57) - /user/randdata/file_17GB.dat" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.780882" level=info msg="Called Lookup (57) - /user/randdata/file_17GB.dat" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:10:12.780901" level=info msg="Calling Attr (58) - /user/randdata/file_17GB.dat" function=Attr package=irodsfs struct=File
time="2023-02-10 14:10:12.780944" level=info msg="Called Attr (58) - /user/randdata/file_17GB.dat" function=Attr package=irodsfs struct=File
time="2023-02-10 14:10:12.782460" level=info msg="Calling Attr (59) - /user/randdata" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.782511" level=info msg="Called Attr (59) - /user/randdata" function=Attr package=irodsfs struct=Dir
time="2023-02-10 14:10:12.782952" level=info msg="Calling ReadDirAll (60) - /user/randdata" function=ReadDirAll package=irodsfs struct=Dir
time="2023-02-10 14:10:12.783021" level=info msg="Called ReadDirAll (60) - /user/randdata" function=ReadDirAll package=irodsfs struct=Dir
time="2023-02-10 14:10:13.908793" level=info msg="Calling Open (61) - /user/randdata/file_17GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-10 14:10:13.920745" level=info msg="Called Open (61) - /user/randdata/file_17GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-10 14:23:53.231040" level=error msg="failed to create a pipe on a dir /tmp/irodsfs_temp_cfj3j0q1ja5ofc174flg" error="open /tmp/irodsfs_temp_cfj3j0q1ja5ofc174flg/pipefile50130264: too many open files" function=newDataBlock package=io struct=AsyncBlockReader
time="2023-02-10 14:23:53.231165" level=error msg="failed to read data for file /user/randdata/file_17GB.dat, offset 17012097024, length 131056" error="open /tmp/irodsfs_temp_cfj3j0q1ja5ofc174flg/pipefile50130264: too many open files" function=Read package=irodsfs struct=FileHandle
time="2023-02-10 14:24:54.995872" level=info msg="Calling Lookup (62) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:54.996260" level=error msg="failed to create a new connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Get package=session struct=ConnectionPool
time="2023-02-10 14:24:54.996298" level=error msg="failed to get an idle connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=AcquireConnection package=session struct=IRODSSession
time="2023-02-10 14:24:54.996319" level=error msg="failed to stat - /MRDataZone/home/user" error="could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:54.996338" level=info msg="Called Lookup (62) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:54.996497" level=info msg="Calling Lookup (63) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:54.996608" level=error msg="failed to create a new connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Get package=session struct=ConnectionPool
time="2023-02-10 14:24:54.996628" level=error msg="failed to get an idle connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=AcquireConnection package=session struct=IRODSSession
time="2023-02-10 14:24:54.996647" level=error msg="failed to stat - /MRDataZone/home/user" error="could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:54.996664" level=info msg="Called Lookup (63) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:59.826179" level=info msg="Calling Lookup (64) - /user" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:59.826404" level=error msg="failed to create a new connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Get package=session struct=ConnectionPool
time="2023-02-10 14:24:59.826448" level=error msg="failed to get an idle connection - could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=AcquireConnection package=session struct=IRODSSession
time="2023-02-10 14:24:59.826469" level=error msg="failed to stat - /MRDataZone/home/user" error="could not connect to specified host and port (irods.local:1247) - dial tcp 192.168.18.216:1247: socket: too many open files" function=Lookup package=irodsfs struct=Dir
time="2023-02-10 14:24:59.826488" level=info msg="Called Lookup (64) - /user" function=Lookup package=irodsfs struct=Dir
```
</details>

<details>
  <summary>lsb_release</summary>

```bash
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```
</details>

<details>
  <summary>irodsfs --version</summary>

```bash
{
  "clientVersion": "v0.7.5",
  "gitCommit": "20774890f08f0abe3f3529d311af561823417a74",
  "buildDate": "2022-07-28T17:50:26Z",
  "goVersion": "go1.18.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
</details>

<details>
  <summary>irodsfs.conf</summary>

```
host: irods.local
port: 1247
proxy_user: user
client_user: user
zone: Zone
password: 1234
MountPath: /home/user/iRODS/

authscheme: "native"
ssl_ca_cert_file: "/home/user/.irods/irodsfs.pem"
ssl_encryption_key_size: 32
ssl_encryption_algorithm: "AES-256-CBC"
ssl_encryption_salt_size: 8
ssl_encryption_hash_rounds: 16
cs_negotiation: true
cs_negotiation_policy: "CS_NEG_REQUIRE"

foreground: false
allow_other: false

path_mappings:
  - irods_path: /Zone/
    mapping_path: /
    resource_type: dir
```
</details>

**Comment by praveenivp** [comment] 2023-02-10 15:00
Also freezes with the new version 0.8.6.
```bash
[user@login0 test]$ irodsfs --version
{
  "clientVersion": "v0.8.6",
  "gitCommit": "5660778bc87e16ada1a3a4e3cddf4ac74ca717e7",
  "buildDate": "2023-01-30T19:40:05Z",
  "goVersion": "go1.18.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}
[user@login0 test]$ rsync -av --info=progress2,stats2 ~/iRODS/user/randdata/file_17GB.dat .
sending incremental file list
file_17GB.dat
 16,978,870,272  95%  123.71MB/s    0:00:06 
```

**Comment by iychoi** [comment] 2023-02-10 17:49
I will try to reproduce the issue on my machine. Thanks for the report.

**Comment by iychoi** [comment] 2023-02-23 04:21
It looks like it has opened too many files at the same time.

`time="2023-02-10 14:23:53.231040" level=error msg="failed to create a pipe on a dir /tmp/irodsfs_temp_cfj3j0q1ja5ofc174flg" error="open /tmp/irodsfs_temp_cfj3j0q1ja5ofc174flg/pipefile50130264: too many open files" function=newDataBlock package=io struct=AsyncBlockReader`

This is because for each file handle, iRODS FUSE Lite creates a local pipe file. So it requires not only local disk space, but also file descriptors to handle the file and the socket.

I'm working on a fix that uses DRAM instead of pipe. I'll leave a comment when it's available.

**Comment by iychoi** [comment] 2023-02-27 23:06
Can you retry the same test with `v0.8.8`?

**Comment by praveenivp** [comment] 2023-02-28 00:58
It looks like I get the same error. Thanks for the effort.
```bash
[user@hpc-login0 test]$ irodsfs -v
{
  "clientVersion": "v0.8.8",
  "gitCommit": "d8041f9c75ed5152101bdc1f468fa591e564e628",
  "buildDate": "2023-02-27T23:05:53Z",
  "goVersion": "go1.18.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}
[user@hpc-login0 test]$ rsync -av --info=progress2,stats2 ~/iRODS/pvalsala/randdata/file_20GB.dat .
sending incremental file list
file_20GB.dat
 16,966,844,416  79%  123.49MB/s    0:00:35 
```

<details>
<summary>log file</summary>
```bash
time="2023-02-28 01:48:15.690947" level=info msg="Calling Open (29) - /pvalsala/randdata/file_20GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-28 01:48:15.704871" level=info msg="Called Open (29) - /pvalsala/randdata/file_20GB.dat, mode(r)" function=Open package=irodsfs struct=File
time="2023-02-28 01:50:28.182046" level=error msg="failed to create a pipe on a dir /tmp/irodsfs_temp_cfukto21ja5uio30rou0" error="open /tmp/irodsfs_temp_cfukto21ja5uio30rou0/pipefile4144480347: too many open files" function=newDataBlock>
time="2023-02-28 01:50:28.182177" level=error msg="failed to read data for file /pvalsala/randdata/file_20GB.dat, offset 17012097024, length 131056" error="open /tmp/irodsfs_temp_cfukto21ja5uio30rou0/pipefile4144480347: too many open fil>
```
</details>

**Comment by iychoi** [comment] 2023-02-28 01:13
Sorry to hear that.
Can you share the full log? The error message `failed to create a pipe on a dir /tmp/irodsfs_temp_cfukto21ja5uio30rou0` part is very weird because I removed all the codes that use `pipe`. So it shouldn't get that error.

**Comment by iychoi** [comment] 2023-03-10 03:26
Close the issue as we don't use pipe anymore.

**Closed by iychoi** 2023-03-10 03:26 UTC
Labels: bug, enhancement

**Comment by praveenivp** [comment] 2023-03-29 12:04
Sorry, I was on a holiday. Indeed, you are right about the `pipe`. I was using a script for mounting and setup irods which used the old executable even though the new version is on the `PATH`. After proper mounting, I tried copying 20 GB and it worked without any issue.

**Comment by iychoi** [comment] 2023-03-30 02:16
Thanks for the update!
Great to hear that it worked!
